baseURL = "https://www.UtahCountyBees.com"
title = "UtahCountyBees"
theme = "universal"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableRobotsTXT = true
canonifyURLs = true

# Define the number of posts per page
paginate = 2

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "report"
    name = "Report A Swarm"
    url  = "/swarm/"
    weight = 2

[[menu.main]]
    identifier = "contact"
    name = "Contact US"
    url  = "/contact/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Local Honey"
    url  = "/honey/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "phone"
    url = "tel:801-734-9481"
    pre = "<i class='fas fa-2x fa-mobile-alt'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/groups/230607091341050"
    pre = "<i class='fab fa-2x fa-facebook'></i>" 

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:swarm@utahcountybees.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"



# Top par contact us
[params.topbar]
    enable = true
    text = "Call or Text us --------->"

[params.features]
    enable = true

[params.carousel]
    enable = true	
	
[params]

	author = "UtahCountyBees"
	facebook = "https://www.facebook.com/groups/230607091341050"
	sitename = "Utah County Bees - Report a Swarm"
    #Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"
	
	logo = "img/logo.png"
	logo_small = "img/logo.png"
	
    about_us = "<p>Just a few local beekeepers from Utah County that want to save some honeybees.</p>"
    copyright = "Copyright (c) 2014 - 2024, UtahCountyBees; all rights reserved."
    # Format dates with Go's time formatting
    date_format = "January 13, 2021"
    
	address = """<p class="text-uppercase"><strong>UtahCountyBees.com</strong>
        <br>Serving Spanish Fork, Springville, Salem, Payson, Santaquin, Provo, Orem</p>"""
		
[languages]	
	[languages.en]
		languageName = "English"
		languageCode = "en-us"
		weight = "1"
